name: Check gfall data update workflow

on:
  schedule:
    - cron: '0 0 * * 0'  #runs on every Sunday midnight
  workflow_dispatch:
  
env:
  SOURCE_URL: http://kurucz.harvard.edu/linelists/gfall/gfall.dat           #URL of the gfall line lists 
  CHANGES_URL: http://kurucz.harvard.edu/linelists/gfall/changesall.tab      #URL of the changes mentioned by Kuruz
  CREATION_URL: http://kurucz.harvard.edu/linelists/gfall/creationdates.dat  #creation date of each data
  README_URL: http://kurucz.harvard.edu/linelists/gfall/00gffix.readme       #readme file at Kuruz website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout github repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Download data
        id: download_data
        run: |
          mkdir -p linelists/gfall
          wget -qO linelists/gfall/gfall.dat http://kurucz.harvard.edu/linelists/gfall/gfall.dat 
          echo "1"
          wget -qO linelists/gfall/changesall.dat $CHANGES_URL 
          echo "2"
          wget -qO linelists/gfall/creationdates.dat $CREATION_URL
          wget -qO linelists/gfall/readme.dat $README_URL
          
      - name: Compare changes
        id: compare
        run: |
          git add .
          echo "3"
          git diff --quiet --exit-code --cached
          echo "4"

      - name: Commit files to git
        id: commit_changes
        if: ${{ steps.compare.outputs.change == 1 }}
        run: |
          git commit -m "New dataset added"

      - name: Push changes
        if: ${{ steps.compare.outputs.change == 1 }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
